### ISSUE TITLE
Crash  with 436eae89982c25efe3c6bd8e2850752c6b17251a and above 

### ISSUE THREAD

**Issue by pmaziere** [nilsbraden/ttrss-reader-fork#331]
While 1.90.1 is working fine, I build and installed 436eae8, but it seems that @mdewilde PR makes ttrss-reader crash on with my Replicant 4.2 0004 Samsung S (I9000). Same goes for the current HEAD.

logcat does not seem to show anything useful:

```
I/ActivityManager( 1827): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttrssreader/.gui.CategoryActivity bnds=[0,452][96,572]} from pid 2062
I/ActivityManager( 1827): Start proc org.ttrssreader for activity org.ttrssreader/.gui.CategoryActivity: pid=6509 uid=10039 gids={50039, 3003, 1015, 1028
I/ActivityManager( 1827): Process org.ttrssreader (pid 6509) has died
```

**Comment by pmaziere** [comment]
confirmed with 1.91

```
I/ActivityManager( 1783): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttrssreader/.gui.CategoryActivity bnds=[0,452][96,572]} from pid 2030
I/ActivityManager( 1783): Start proc org.ttrssreader for activity org.ttrssreader/.gui.CategoryActivity: pid=22532 uid=10039 gids={50039, 3003, 1015, 1028}
W/XPrivacy(22532): Hooking package=org.ttrssreader
E/AndroidRuntime(22532): 	at org.ttrssreader.net.JSONConnector.init(JSONConnector.java:227)
E/AndroidRuntime(22532): 	at org.ttrssreader.controllers.Controller.getConnector(Controller.java:493)
E/AndroidRuntime(22532): 	at org.ttrssreader.gui.MenuActivity.doRefresh(MenuActivity.java:555)
E/AndroidRuntime(22532): 	at org.ttrssreader.gui.CategoryActivity.doRefresh(CategoryActivity.java:153)
E/AndroidRuntime(22532): 	at org.ttrssreader.gui.MenuActivity.refreshAndUpdate(MenuActivity.java:538)
E/AndroidRuntime(22532): 	at org.ttrssreader.gui.MenuActivity.onResume(MenuActivity.java:263)
W/ActivityManager( 1783):   Force finishing activity org.ttrssreader/.gui.CategoryActivity
W/ActivityManager( 1783): Activity pause timeout for ActivityRecord{41a017f8 u0 org.ttrssreader/.gui.CategoryActivity}
I/ActivityManager( 1783): Process org.ttrssreader (pid 22532) has died.
```

**Comment by nilsbraden** [comment]
Can you try with this build please: https://github.com/nilsbraden/ttrss-reader-fork/releases/tag/Test_Issue_%23331

The stacktrace seems to be missing some lines but I figured the only exception in this line was a NPE in the formatException() method. This should be fixed now.

**Comment by pmaziere** [comment]
It still crashes with a47b269d91d918f06366a717e667915834353dd8
but not any more with 43df4215688287e35cd6ca049d302884b3389125

thanks
